baseURL = "https://takint.github.io/"
relativeURLs = false
languageCode = "en-us"
title = "Jim Le: Full Stack Developer in Vacounver, Canada"
theme = "hugo-geo"
disqusShortname = "takint"
enableRobotsTXT = true
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "taki.lnt@gmail.com"

	profilepic = "img/ava3.jpg"
	
	title = "Jim Le"
	subtitle = "Full Stack Developer in Vacounver, Canada"
	description = "I'm Ngoc Tin Le (Jim), a Software Developer specialized in Microsoft Technologies. I aim to participate in building awesome software with ASP.NET Core (C#) and JavaScript."
	defaultKeywords = ["Ngoc Tin Le", "Jim Le", "developer", "programming", "full-stack", "asp.net core", "software development", "engineer"]

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/ngoc-tin-le/"
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/takint"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/takint"
	[[params.socialbuttons]]
	faicon = "stackoverflow"
	url = "https://stackoverflow.com/users/1345472/takint"
	
	[[params.navlinks]]
	name = "Resume"
	url = "resume/"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"
	
	[[params.navlinks]]
	name = "About"
	url = "about"